### PR TITLE
3D Weapon and new Clothing Dialog and Save Settings and fix Issue #168

### PR DESCRIPTION
**Pull request by Devilfloh**
- save settings in active arma 3 profile
- fix language in store and spawn vehicle [#168](https://github.com/ArmaLife/Altis/issues/168)
- 3D Weapon Menu http://www.directupload.net/file/d/4264/oq66rb42_jpg.htm
- new Clothing Shop Dialog http://www.directupload.net/file/d/4264/kgygrvyh_jpg.htm

### CODE REVIEW

**Comment by danielstuart14** [comment]
I liked the idea, but where's the exit button?

**Comment by Heavybob** [comment]
Checking build out, pictures look awesome.

**Comment by Devilfloh** [comment]
close button added.

ignore the color (title)

**Comment by danielstuart14** [comment]
Okay, let's go...

I liked the clothing shop, but you can't use grid. It must be safezone.

About the weapon shop. it's useless, and even makes no sense when talking about general store.
It should show the image of the item, not it in 3d.

I'll manual merge the saving configuration stuff.

**Pull request closed without merging**
