### PR TITLE
Functions: Tags: Don't show player name if head is covered

### PR DESCRIPTION
**Pull request by danielstuart14**
@Heavybob

### CODE REVIEW

**Comment by Heavybob** [comment]
you are correct @tkcjesse, it is goggles.

// Hats

"H_Shemag_olive",
"H_ShemagOpen_tan",
"H_ShemagOpen_khk",

// Glasses

"G_Balaclava_blk",
"G_Balaclava_combat",
"G_Balaclava_lowprofile",
"G_Balaclava_oli",
"G_Bandanna_aviator",
"G_Bandanna_beast",
"G_Bandanna_blk",
"G_Bandanna_khk",
"G_Bandanna_oli",
"G_Bandanna_shades",
"G_Bandanna_sport",
"G_Bandanna_tan"

// Uniforms

"U_O_GhillieSuit",
"U_I_GhillieSuit",
"U_B_GhillieSuit"

**Comment by Heavybob** [comment]
19:28:22 File mpmissions\__CUR_MP.Altis\core\functions\fn_playerTags.sqf, line 39
19:28:22 Error in expression <(count _sPos > 1 && {_distance < 15} && !{(headgear _x) in _masks}) then {
_text>
19:28:22   Error position: <!{(headgear _x) in _masks}) then {
_text>
19:28:22   Error Generic error in expression
19:28:22 File mpmissions\__CUR_MP.Altis\core\functions\fn_playerTags.sqf, line 39
19:28:22 Error in expression <(count _sPos > 1 && {_distance < 15} && !{(headgear _x) in _masks}) then {
_text>
19:28:22   Error position: <!{(headgear _x) in _masks}) then {
_text>
19:28:22   Error !: Type code, expected Bool
19:28:22 File mpmissions\__CUR_MP.Altis\core\functions\fn_playerTags.sqf, line 39
19:28:22 Error in expression <(count _sPos > 1 && {_distance < 15} && !{(headgear _x) in _masks}) then {
_text>


Spamming every second, no playertags are showing.

**Comment by Heavybob** [comment]
I helped :+1:

**Comment by danielstuart14** [comment]
A lot

**Comment by Heavybob** [comment]
Close thread please

**Pull request closed without merging**
