### PR TITLE
Lets avoid anything weird happening

### PR DESCRIPTION
**Pull request by Liam0**
Why did we stop preparing stuff before sending it to DB?
Dont save position if player is in water just incase
Is active column even worth keeping in containers doesn't seem to be used anymore?

### CODE REVIEW

**Comment by Liam0** [comment]
it might not be needed anymore but it would be nice to either **use it or not use it** instead of this mixed stuff all around the DB

**Comment by fEcAlMaTteR** [comment]
@Liam0 Blunder on my part.  
`_position = if(_side == civilian) then {[_position] call DB_fnc_mresArray} else {"[]"};`
Save as a string to avoid un needed mres call.

**Comment by danielstuart14** [comment]
I think these Array to String and String to Array functions are useless. I can't found the reason we use it... Also, if you take a look into the functions, they convert a value to another, but don't convert it back to the original value when retriving...

**Comment by Liam0** [comment]
it's probably related to some of the older ways of inserting data to the database the question is just if its still needed with extdb or if it can handle it fine on its own because then we might aswell remove it entirely and reduce all these extra calls

**Pull request closed without merging**
