### PR TITLE
Update fn_wantedProfUpdate.sqf

### PR DESCRIPTION
**Pull request by tkcjesse**
Fixes it.

### CODE REVIEW

**Comment by Jawshy** [comment]
Could you please describe what this change does for posterity?

**Comment by tkcjesse** [comment]
I mean originally it was:
_query = format["UPDATE wanted SET wantedName='%1' WHERE wantedID='%2'",_uid,_name];

If you think the wantedName is equal to your UID, then you're sadly mistaken... Not sure how you want me to explain this...

**Comment by sargken** [comment]
^^

**Comment by Jawshy** [comment]
I was asking if you could explain what this changes or fixes so people looking back on this pull request can understand what it changed.

**Comment by danielstuart14** [comment]
Updates the name in wanted DB if player changes the name

**Comment by sargken** [comment]
@Jawshy I give you alot of credit you do put alot of effort into the documentation.

**Pull request merged**
