### PR TITLE
(Optional) Side separated Cash/Bank | Increased paycheck for higher ranking cop/medic

### PR DESCRIPTION
**Pull request by fEcAlMaTteR**
**Config_Master**
Added: Money settings section
Merged: Bank account/Paycheck sections into Money settings
Added: separate_bankBySide (BOOL) Default: false | Separate cash/bank for cop,med,civ?
Added: paycheck_%SIDE%Multiplier (FLOAT) Default: 0 | Increment for pay increase vs side level 0 = Disabled, % / 100 IE: 0.25 would give a 25% increase per level

**Headless Client Compatible**

### CODE REVIEW

**Comment by CanadienFr** [comment]
It working or not ? i will use it.

**Comment by fEcAlMaTteR** [comment]
Yea it works

**Comment by CanadienFr** [comment]
Ok thanks for your confirmation ! :+1:

**Comment by sargken** [comment]
You should do a separate pull with just the paycheck multiplyer

**Comment by Jawshy** [comment]
:+1: for paycheck multiplier.

**Pull request closed without merging**
