### PR TITLE
Madrid / Gordan Veh Options

### PR DESCRIPTION
**Pull request by Heavybob**
Adds support for Madrid  / Gordan. Strips veh and removes turrets so they aren't op or look silly.

### CODE REVIEW

**Comment by Heavybob** [comment]
images akamai steamusercontent

**Comment by Heavybob** [comment]
I did not include them into the veh config as they should be optional for server owners but if they import them into the stores, weapons and turrets will be removed automatically.

**Comment by BoGuu** [comment]
Under this mind set, all armed vehicles should technically be disarmed. If somebody wishes to add a new vehicle, let them figure out how to google what ammo they use and copy pasta it themselves. Try to minimise the spoon feeding?

**Comment by Heavybob** [comment]
If we had that mentality, nothing would be done. This merge is optional, if the higher forces don't want it then thats fine.

**Comment by tkcjesse** [comment]
Yeah, no point in doing it for just specifically these two vehicles... It's not hard to adapt and just use whats there liek @BoGuu pointed out. I'll like it to the wiki and also put the syntax if its that hard to understand...

**Pull request closed without merging**
