### PR TITLE
Add New Job/Mission. Fuel Transport to Gas Station

### PR DESCRIPTION
**Pull request by Zeronova**
A new Transport Mission.
Limited filling rate of Gas stations,
More distance = higher income.
if you like it, use it!

BE Filters Not updated

### CODE REVIEW

**Comment by danielstuart14** [comment]
Any print?

**Comment by Zeronova** [comment]
What do you mean?? Screenshot??
Sorry! I'm a big noob with github... :-)

**Comment by danielstuart14** [comment]
yeah, screenshots... Map markers, dialogs, etc.
So, we can see how it's before merging

**Comment by Zeronova** [comment]
pos1
pos2
fill
short
long
win

**Comment by danielstuart14** [comment]
going to update and merge it later, but if you want to rebase with latest changes, I'll merge it for you.

**Comment by Kimax89** [comment]
Any news on this?

**Comment by MrHeavyMetal** [comment]
this looks awesome would love to see this added

**Comment by danielstuart14** [comment]
added, thx

**Pull request closed without merging**
