### PR TITLE
New EVH - onPlayerDisconnected - WIP

### PR DESCRIPTION
**Pull request by sargken**
I'm going to expand upon #66 and fix the issue @Heavybob brought up.

### CODE REVIEW

**Comment by Heavybob** [comment]
Thanks @sargken

**Comment by tkcjesse** [comment]
What issue?

**Comment by Heavybob** [comment]
ok will test it later
got an issue with ArmaLife/Altis@fe38dd0
if a player is joining the server and is stuck on debug island
and they disconnect
it will overwrite the gear that hasn't assigned
and players loose gear
just had it happen to a guy

**Comment by tkcjesse** [comment]
That would happen regardless. Since in the: https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/functions/fn_escInterupt.sqf

It calls SOCK_fnc_updateRequest.

So this would already have been an issue, since it syncs data anytime you hit the abort button. See lines 33 & 34 in that file.

**Comment by sargken** [comment]
Then why would you even need this? Its 2 seconds a difference for the refresh time.

**Comment by tkcjesse** [comment]
It's for ALT+F4 disconnects, client crashes.

**Comment by tkcjesse** [comment]
Some example reasons listed here: https://github.com/ArmaLife/Altis/pull/66

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/7dee4449350ec81608c24e7c12c4c407bd520247

**Comment by sargken** [comment]
You should do the same for the sockwt update for the esc interrupt.

**Comment by tkcjesse** [comment]
@danielstuart14 
This happens regardless of the Event Handler. Since in the: https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/functions/fn_escInterupt.sqf

It calls SOCK_fnc_updateRequest.

So this would already have been an issue, since it syncs data anytime you hit the abort button. See lines 33 & 34 in that file.

May want to revise the esc interupt to include the same..

**Comment by sargken** [comment]
Socket*

**Comment by danielstuart14** [comment]
can't we just remove it from escInterrupt? As it is already being called when aborting?

**Comment by danielstuart14** [comment]
forget... we can't as it needs update database even if player just wants to go to lobby

**Pull request closed without merging**
