### PR TITLE
Persistent Settings

### PR DESCRIPTION
**Pull request by tkcjesse**
Add thirst & hunger persistence.

### CODE REVIEW

**Comment by clackd1amond** [comment]
Just tested it on my server. Works perfectly. Thank you! Saving health and position would be an awesome addition to this.

**Comment by Heavybob** [comment]
I did have a crack with this test but I am going to wait for a little bit for a few others to test.
Experienced a handful of errors *pros due to me merging conflicts with my own build*

**Comment by AveUrsus** [comment]
Do not know why - hunger and thirst values are not saving to DB for me.
If i edit it in DB directly  -values set up correctly on character loading. 
RPTs are clear

**Comment by tkcjesse** [comment]
Did you change the setting in the  master  config to true????

**Comment by tkcjesse** [comment]
Also its only set to write the changes when hudUpdate is called. So if you're doing it in debugbe sure to call hudUpdate once you set the values. Or let your health drop naturally.

**Comment by tkcjesse** [comment]
Meant food/water in the above.

**Comment by tkcjesse** [comment]
@danielstuart14 - If you want to merge it go ahead. 
Up to you. I closed this. I'm done submitting things here. The aids is real.

**Pull request closed without merging**
