### PR TITLE
Editing the vInteraction menu for othe languages

### PR DESCRIPTION
**Pull request by silvercn**
In other languakes like german, you just see "Vehicle" on most buttons, and don´t know what action is called behind. Easy to fix when we make them a bit more wider.

### CODE REVIEW

**Comment by silvercn** [comment]
http://images.akamai.steamusercontent.com/ugc/317872565971799111/1D2EF3C77A3B39699DF15C29EF6A6F0FE6C52EA5/

**Comment by dardothemaster** [comment]
Finally!

**Comment by Liam0** [comment]
Try to put a screenshot of what it looks like in the original language?

**Comment by clackd1amond** [comment]
It doen't make wider background and title. So buttons go out of borders.

**Comment by silvercn** [comment]
Will change that in a second

**Pull request merged**
