### PR TITLE
Mining Percents (HotFix) 

### PR DESCRIPTION
**Pull request by dardothemaster**
Here's the hotfix (Actually a commit that git missed) for the mining percent. Tested and working.

### CODE REVIEW

**Comment by silvercn** [comment]
Works. :+1:

**Comment by dardothemaster** [comment]
*heavy breath*

**Comment by danielstuart14** [comment]
it has conflicts with the main build

**Comment by fresqo** [comment]
i did something similar once, i found setting life_action_inUse false then true mid switching from gather to mine file causes spam bugs when people spam windows key. probably something to check when testing.

**Pull request closed without merging**
