### PR TITLE
check cops online

### PR DESCRIPTION
**Pull request by clackd1amond**

### CODE REVIEW

**Comment by Heavybob** [comment]
Thanks @clackd1amond for doing this.

**Comment by Heavybob** [comment]
Will test in a few hours./

**Comment by Heavybob** [comment]
testing now

**Comment by Heavybob** [comment]
Merge Request, this works no errors.

**Comment by Heavybob** [comment]
*Would include to prevent bolt cutting of the medical box that the gold bars are stored and prevent use of explosives on the box too.

**Comment by clackd1amond** [comment]
Will now add more checks and add cop count setting to master

**Comment by Heavybob** [comment]
good idea

**Comment by clackd1amond** [comment]
finished #75

**Pull request closed without merging**
