### PR TITLE
Clothing Preview - Dynamic Positions

### PR DESCRIPTION
**Pull request by sargken**
#8 This adds in two settings into the config master to allow the black box
to be turned on and off plus for the clothing shop to randomly be
placed. @Heavybob Check this out.

### CODE REVIEW

**Comment by Heavybob** [comment]
Checking out now, Give me 10 mins and I'll drop a reply.

**Comment by sargken** [comment]
@danielstuart14 If you want i can condense to 1 "Flag" like it was originally. I think it would work better this way also.

**Comment by danielstuart14** [comment]
it was closed cuz it set our current method as secondary. 
These two flags doesn't make sense, because one doesn't work without the other.

Later I'll add the markers on map feature, and an option to disable teleport feature.

**Comment by Heavybob** [comment]
@sargken Works perfectly. I'll get around to giving you better coords for Kart.

**Comment by sargken** [comment]
@danielstuart14 I will condense the flags into a single flag like original and have the default set to the black box? Does that sound right, and I already know that 2 flags don't make since but i didn't know the reason for why it was closed. That's why i made 2 flags here. I think you should setup a ArmaLife Discord chat for us 3 @danielstuart14 @Heavybob so we can all communicate on a closed channel chatbox. https://discordapp.com/

**Comment by Heavybob** [comment]
All the cool kids use teamspeak. Address: GGS.SX

**Comment by sargken** [comment]
Well its a good chatbox solution for communication, plus its free.

**Comment by Heavybob** [comment]
Might as well use facebook...

**Comment by danielstuart14** [comment]
Yes @sargken, this way I'll merge it.

I think google hangout is a good choice (Web + multiplataform + mobile), what you think, guys?

**Comment by sargken** [comment]
@danielstuart14 Its up to you guys.

**Comment by Heavybob** [comment]
I am cool with google hangout.

**Comment by danielstuart14** [comment]
https://plus.google.com/104705460475757935999/
Just add me and I'll do a chat with you

**Comment by sargken** [comment]
@danielstuart14 Fixed the one Flag

**Comment by Heavybob** [comment]
Having a shit time trying to figure out hangouts. Would suggest to join me and ken on teamspeak dan. We are already on chatting.

**Comment by sargken** [comment]
@danielstuart14 https://discord.gg/0lp9duZY373828Tp

**Pull request merged**
