### PR TITLE
5 second minimum respawn time.

### PR DESCRIPTION
**Pull request by Kimax89**
A simple check to make sure that server-owners cant set the respawn_timer below 5 seconds.

### CODE REVIEW

**Comment by Kimax89** [comment]
tested and working.

**Comment by sargken** [comment]
Not framework your limiting server owners for no reason put it on ur server but others may want a tdm.

**Comment by Heavybob** [comment]
Don't understand why this would be put in.

**Comment by tkcjesse** [comment]
I mean if people set it to zero, let them learn what stupid problems come with. In regards to it showing the two timers, just hide one. lmao.

**Comment by Heavybob** [comment]
I don't see a point to putting red tape around the re spawning system unless it is critically breaking the game when you make it less than 5 seconds.

**Comment by Kimax89** [comment]
as far as i can remember it actually does conflict if you try to respawn faster than the respawndelay in the mission, but i will test that and come back with a result.

**Comment by Kimax89** [comment]
@sargken The respawntime was restricted to 5 seconds for a looooong time, but thanks to me and your welcome, its now possible to adjust the timer from the Config_Master. so where do i limit the server owners again?

@tkcjesse i believe that everything should be idiot-proof and regards to the 2 timers that are showed, we just need to remove the one from the mission.

@Heavybob I'm testing this within the next 10 minutes.

Last note: Does it hurt to add this?

**Comment by Kimax89** [comment]
Yes. it does conflict if the respawn_timer is sat below 5 seconds and a player tries to respawn within those 5 seconds. They wont respawn normally and will respawn on the "Respawn Island".

**Pull request merged**
