### PR TITLE
Fix for persistent position | Server available while hc enabled & not ready/not working

### PR DESCRIPTION
**Pull request by fEcAlMaTteR**
Fixed error in HC code from persistent positioning.

HC_Enabled = true doesn't require headless client to operate.  IE server handles queries while hc is starting and resumes handling upon hc disconnect.

Key Management handled by only the server.
Initial queryRequest handled by only the server.
Variable on vehicles "dbInfo" is public to allow both server & hc to handle impounding regardless of which handled the spawning.

### CODE REVIEW

**Comment by fEcAlMaTteR** [comment]
Plan to fix issues with headless client with vehicle impounding in this branch as well.  Seems to be related to hc using (owner _unit) as this will return 0 (RANY) for clients.

**Comment by fEcAlMaTteR** [comment]
Another issue for the headless client (linux only) Runtime is limited to ~2.5 hours.  At this point the hc is kicked.  Need to add a timed shutdown routine to stop the hunting zone and tell everyone to use the server for queries while the HC is restarting.

**Comment by fEcAlMaTteR** [comment]
And another issue: Vehicles spawned by hc don't return keys after re-logging.  If hc disconnects vehicles are seen as rentals by the server.

**Comment by fEcAlMaTteR** [comment]
Hold off on this.  Needs further testing.  HC is still broadcasting to everyone

**Comment by fEcAlMaTteR** [comment]
OK, seems ready.  Fixed issue with impounding.

**Comment by fEcAlMaTteR** [comment]
@NiiRoZz How so?

**Comment by NiiRoZz** [comment]
Because you don't need to recreate owner id, look in init.sqf in core and init.sqf in life server, enter variable in player, the variable it's the owner id, just when people update life_hc don't use this variable, other people are very ...

**Comment by NiiRoZz** [comment]
It's not all a joke, just your ownerid ..

**Comment by NiiRoZz** [comment]
Just only when the first push of HC all work, but when i'mais Come Back all modify HC but all don't know how it work ...

**Comment by fEcAlMaTteR** [comment]
ownerID was added to pass to the headless client for vehicle impounding at the garage.  There are a few other ways but this seemed the most logical.  If you go back before these updates try garaging a vehicle...  hc broadcasts to everyone and store vehicle in garage disapears because the hc CANNOT get the ownerID to use publicVariableClient without asking the server.

**Comment by NiiRoZz** [comment]
http://www.noelshack.com/2016-10-1457339060-screenshot-2016-03-07-09-23-21.png I HAVE ALREADY DO THIS, AND I DON'T USE QUERY REQUEST !!

**Comment by NiiRoZz** [comment]
Please just look before change, i Will redo all

**Pull request merged**
