### PR TITLE
TearGas in Life Format

### PR DESCRIPTION
**Pull request by trinitynet**
Not tested, Pressing esc bypasses the effects..

### CODE REVIEW

**Comment by trinitynet** [comment]
forgot to change file names in the headers...

**Comment by Kimax89** [comment]
Du a clean pull request. this is never gonna be merge'd when you have a "Merge remote-tracking branch".

**Comment by trinitynet** [comment]
meh, github being github. wont let me do it another way. if somone else wants to do it thats fine too

**Comment by sargken** [comment]
I always have those issues. Ppl telll me to clean it then i try and fuck up commits.

**Comment by tkcjesse** [comment]
To have "cleaner" commits, i'd suggest deleting your repo prior to starting a new project, then re-forking. If you have your own stuff or what not, just create an un-linked repo. That's what I usually do. Every time I want to do a new pull I just re-fork to have a clean slate then do 1 commit. I use to use the browser, but the browsers trash.

**Comment by Liam0** [comment]
Haha yeah last time i tried to squash my commits together it did not turn out the way i wanted it to lol! i do the same as @tkcjesse

**Comment by TAWTonic** [comment]
Or even better don't put WIP edits in your Github work folder, do it outside till you have a clean commit separate from others.

**Comment by trinitynet** [comment]
@TAWTonic  yeh thats what ive been doing but my GitHub is messed up and have to use GitShell and its a pain lol

**Comment by trinitynet** [comment]
i just wont post anything till i reinstall win :D

**Pull request closed without merging**
