### PR TITLE
pay for fuel on gasstations

### PR DESCRIPTION
**Pull request by AveUrsus**
pay for fuel on gasstations. Its for #50

### CODE REVIEW

**Comment by danielstuart14** [comment]
I like the idea... WIll push, and maybe today I'll add a check to disable or enable it from config_master, and set a price for each vehicle class. (air, car, truck, etc.)

**Comment by danielstuart14** [comment]
I'm going to test.

**Comment by tkcjesse** [comment]
@danielstuart14 Note that fuelPay.sqf uses life_fnc_MP & not remoteExec

**Comment by danielstuart14** [comment]
yeah, I'll clean it.

**Comment by Heavybob** [comment]
Looks like I am out of the job. @danielstuart14 you can test this. I hate fuel, its too realistic.

**Comment by sargken** [comment]
@danielstuart14 @AveUrsus I would suggest adding in an addaction that would say pay for gas. So the second you pull up it doesn't just start to charge you money.

**Comment by Heavybob** [comment]
Probs a prompt yes or no.

**Comment by Heavybob** [comment]
_action = [
	"Pay for Gas?",
	"WARNING",
	"Yes",
	"No"
] call BIS_fnc_guiMessage;

if(_action) then {

**Comment by Kimax89** [comment]
Should'nt it be: "You dont have enough money"?

**Comment by tkcjesse** [comment]
^ yes.

**Comment by NiiRoZz** [comment]
I Will put my script will automaticly price change by type of vehicle, and active or not in config_Master.

**Comment by NiiRoZz** [comment]
Need to close, script updated in #148

**Pull request closed without merging**
