### PR TITLE
Master

### PR DESCRIPTION
**Pull request by jlillis**
Two small fixes - the first adds some missing variables to allowedVariables[] in Spyglass, another fixes an error in altislife.sql that was preventing the database tables from being created.

### CODE REVIEW

**Comment by Heavybob** [comment]
Why did you do this?

**Comment by tkcjesse** [comment]
Yeah. The SQL file is fine. I'll commit the allowedVariables. However, you should update your sql version...

**Comment by jlillis** [comment]
Didn't realize this didn't happen in newer versions on MySQL. Updating to the latest version isn't an option for me, sadly. The Spyglass stuff should be useful.

**Comment by jlillis** [comment]
Also, you might want to add a note for Linux users that the minimum version needed is 5.6.5 but the Debian stable repos only ship 5.5 currently.

**Pull request closed without merging**
