### PR TITLE
trunk dupe

### PR DESCRIPTION
**Pull request by devShit**

### CODE REVIEW

**Comment by Jawshy** [comment]
Could you provide a description of this pull? Also, you will need to add `trunk_in_use_by` as an exception in Altis/BEFilters/[setVariable.txt](https://github.com/ArmaLife/Altis/blob/master/BEFilters/setVariable.txt).

**Comment by danielstuart14** [comment]
also in config_Spyglass.hpp

**Comment by danielstuart14** [comment]
also, the variable "trunk_in_use_by" should be an array.

So, it won't override the previous name, just add one more.
When the player closes the menu, it is removed from the array.
(Also, it should check if the unit in array isn't null, to prevent any bug)

**Comment by devShit** [comment]
i dun know how to edit this pull

**Pull request closed without merging**
