### PR TITLE
Added Land_Cargo_Tower

### PR DESCRIPTION
**Pull request by Heavybob**
Tested this and it works fine. Just need to change fn_)houseConfig, I hate web github

### CODE REVIEW

**Comment by Heavybob** [comment]
https://github.com/ArmaLife/Altis/pull/516 This one goes with this merge.

**Comment by Heavybob** [comment]
Tested and works perfectly. Doors work, crates can be stored. Spawning works. No other changes should be required as everything works.

**Comment by tkcjesse** [comment]
Why do you have 12 crates possible for the building? Does it even have the potential to hold that many?

**Comment by NiiRoZz** [comment]
I just say you, the getBuildingPositions doesn't need this now

**Comment by Heavybob** [comment]
Multiple stories. It has the room to store 12 crates.

**Comment by Heavybob** [comment]
images akamai steamusercontent

**Comment by Heavybob** [comment]
images akamai steamusercontent

**Comment by tkcjesse** [comment]
Idk. Seems silly to me. But whatever.

**Comment by Heavybob** [comment]
Its got heaps of room. It can store stuff on 3 separate levels with 8 rooms.

**Comment by Heavybob** [comment]
MIght be somehting to think about. Options to allow members of gangs to access housing.

**Comment by AmarokGaming** [comment]
This seems super silly - maybe have it locked to gangs instead of any civilian. Can't have every single building all over the place populated with crates.

**Comment by DarkSilencerZA** [comment]
This seems super silly - maybe have it locked to gangs instead of any civilian. Can't have every single building all over the place populated with crates.

**Comment by DarkSilencerZA** [comment]
Now that I think about it, anyone can create a gang - so that wouldn't help the issue.

**Comment by Heavybob** [comment]
Merge can be done. No issues with merge. If we want to restrict it to gangs later on then overall of the housing system should be put into a ticket.

**Comment by tkcjesse** [comment]
Would also like to point out that this will make the tower in Athira HQ buyable.

**Comment by DarkSilencerZA** [comment]
In reality, this is Altis Life, not a war-zone to make every bunker your housing space.

**Comment by sargken** [comment]
I don't think this should be merged it should be left up to server owners as ots not hard to do.

**Comment by tkcjesse** [comment]
Closing. As others have stated, essentially just because you can doesn't mean you should... Also, this is meant to be **somewhat** realistic towards life.

Also, pretty sure it'd have to be added to things like https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/functions/fn_actionKeyHandler.sqf#L74 As well as other files that simply have "House_F"  - Could be wrong though..

Also, this has an issue with the Athira HQ location.

Also, fn_copBreakDoor.sqf would need to be edited as well as nearestDoor I do believe, since once again it uses "House_F" - Could be wrong though..

@danielstuart14 if you disagree, my apologies.

**Pull request closed without merging**
