### PR TITLE
Add TO - Admin/Cop/EMS Message Markers

### PR DESCRIPTION
**Pull request by tkcjesse**
Map markers & message with coords.

Regarding: https://github.com/ArmaLife/Altis/issues/38

### CODE REVIEW

**Comment by danielstuart14** [comment]
after @Heavybob feedback I'll merge.

It will need call from player which called the function the check.
Or, we would need create new functions, that are the same except by the new code, and add the check when calling it from the mission...
Either way, it doesn't seem to be a good approach.

I'll let it as default, no checks needed, no hacky code.

**Comment by tkcjesse** [comment]
@danielstuart14 Okay, so it's not that I'm dumb and just was missing a )? Haha. I figured there was more to it..

**Comment by Heavybob** [comment]
My approval is....
https://www.youtube.com/v/gYNUOkqzcVA?rel=0&autoplay=1

This has some minor silent errors which should be fixed before a official commit. I have not tested messaging to all players yet but coords do work and I love what you did with the markers on map. 

5 min timer is a good choice.

If a user submits an admin message then a police message, it will clean up the previous marker. 

Collecting RPT Logs and will submit in a moment.  Testing everything before submitting my RPT.

**Comment by Heavybob** [comment]
15:51:06 Error in expression <
	_loc = _this select 3;
	_unit = _this select 4;
	if(_from == "") exitWith {};
>
15:51:06   Error position: <select 4;
	if(_from == "") exitWith {};
>
15:51:06   Error Zero divisor
15:51:56 Error in expression <
	_loc = _this select 3;
	_unit = _this select 4;
	if(_from == "") exitWith {};
>
15:51:56   Error position: <select 4;
	if(_from == "") exitWith {};
>
15:51:56   Error Zero divisor
15:53:39 Error in expression <
	_loc = _this select 3;
	_unit = _this select 4;
	if(_from == "") exitWith {};
>
15:53:39   Error position: <select 4;
	if(_from == "") exitWith {};
>

**Comment by tkcjesse** [comment]
@Heavybob

Try that same thing with a player with no numbers and shit
Lol.. I assume the zero divisor has to do with that players name... ?

**Comment by Heavybob** [comment]
I am about to test gang message and the other message to police things. Just wait a few more mins and I'll have everything.

If you have a fix for that silent error, submit a commit and I will test it. Please change the icon colors too :+1:

**Comment by tkcjesse** [comment]
@Heavybob

Since when is there gang message?.....

**Comment by Heavybob** [comment]
Sec, I am inventing features I thought you followed my full request...

**Comment by tkcjesse** [comment]
@Heavybob 
This is your main post:
I have seen this on only one server but feel it should be put into the main build.

When someone txt messages cop, it should display the grid reference of where the origin of the txt came from. Including this minor feature will help those small police forces getting harassed by prank callers.

**Comment by tkcjesse** [comment]
Also your image:

https://cloud.githubusercontent.com/assets/4519067/12410390/be2854e2-bec8-11e5-8cb1-8fb6d4aa6c00.jpg

Shows a private message... which I didn't even touch... so it's certainly that players name. I bet it says the same using the default.

**Comment by Heavybob** [comment]
Re-Testing without the client player brackets. 
*Still Persists*


I will check the master build anyway just to make sure it wasn't a code mixup from your commit. 

@tkcjesse Was referring this this post

@Heavybob
Personal Messages by Cops message to all cops
Personal Messages from Cops to Civs message to all gang members of the civ
Personal Messages from Civ to Cops message to all gang members
Emergency Messages from Civ broadcast to all gang members
Emergency Messages from Civ will contain Grid Reference of Sending Player

That Error still persists. Would you kindly @danielstuart14 check that if @tkcjesse cannot.

Apart from that error, this addition is good. Would ask that you change the colors from white to another color.

**Comment by danielstuart14** [comment]
idk if name is related to zero divisor.
I think a cleaner approach is just adding coords to message, without map markers.

Tomorrow I'll take a look

**Comment by tkcjesse** [comment]
Is the zero divisor only on the user to user message or what one(s) is it on?

**Comment by danielstuart14** [comment]
sometimes adding vars to remoteexec fucks everything up...
I like the idea, tomorrow I'll take a look in the code and merge a part of. 
Probably I won't merge the markers, just the cords

**Comment by Heavybob** [comment]
Make it optional for the markers.

**Comment by tkcjesse** [comment]
It's not exactly easy to make optional due to the way tonic set it up, not exactly worth a huge effort to revamp the system to simply make an option... There's a lot more important things to be done imo. I will not be furthering this from my end at least.

**Comment by Heavybob** [comment]
Error plot thickens,

*have not tested using master yet*

Any user who sends a private message experiences that minor error.

**Comment by danielstuart14** [comment]
even without the changes?

**Comment by Heavybob** [comment]
*have not tested master yet, give me a moment.*

**Comment by Heavybob** [comment]
Someone keeps submitting merg requests to the build and they keep getting accepted putting me 9 merg requests behind then I have to test all these damn merg requests.

**Comment by danielstuart14** [comment]
Most of them are just infos. Don't need to sync with them

**Comment by tkcjesse** [comment]
@danielstuart14 is it intended to be able to open your player menu while restrained? I know a lot of people don't like it because it allows users to lockpick themselves whilst restrained.

**Comment by danielstuart14** [comment]
nop, it isn't.
Just add a check in keyhandler,
Give me a minute

**Comment by Heavybob** [comment]
Good find, will test commit when I have time later tonight.

**Comment by baua1310** [comment]
can you make a Button in the UI there you can check if you want to send your position or not

**Comment by tkcjesse** [comment]
@baua1310 
Logically thinking, my assumption is if you're messaging an Admin/EMS/Police I don't understand why you would ever not want to send your position other than to potentially troll or be bothersome. Considering in real life if you call EMS/Police, you're giving them your location/gps access ;)

What is your reasoning for potentially not wanting to share the location of the request?

**Comment by baua1310** [comment]
I have only thought about a situation like a hostage-taking or a bank robbery there you don't want to show your position to the cops.

**Comment by Heavybob** [comment]
If you have a hostage and want cops to know, drive away from the location  when you submit the text message. Not hard. Just like real life but with payphones :+1:

**Comment by baua1310** [comment]
that`s true

**Pull request merged**
