### PR TITLE
Added BattlEye filters

### PR DESCRIPTION
**Pull request by Jawshy**
Added custom BattlEye filters for [Altis Life RPG v4.3r4](https://github.com/ArmaLife/Altis/releases/tag/v4.3r4). 

The majority of the filters were re-done with the main exception of scripts.txt which is an edited version obtained from Altis Life RPG v4.0. 

These filters have been tested, but further, more extensive testing and refining may be required. 

The filters that generated a .log file were: 
- addMagazineCargo
- addBackpackCargo
- AttachTo
- createVehicle
- deleteVehicle
- remoteExec
- scripts
- selectPlayer
- setDamage
- setPos
- setVariable

### CODE REVIEW

**Comment by danielstuart14** [comment]
```
(uinamespace getvaria" //Enter GUI Editor
 // "inamespace getvariable
```
I think it is wrong

**Comment by danielstuart14** [comment]
also, @Jawshy 
I'll merge it when we get v4.4

Because doesn't make sense push it now, as we are pushing many new commits

**Comment by danielstuart14** [comment]
By @DarkSilencerZA 
```
7 "" !="removeBackpack this; removeAllWeapons this;" !"^["true", ""] [[\d:-]+ group, \d+]$"
Use that in your remoteexec.txt
Bam done
```

**Comment by Jawshy** [comment]
> I think it is wrong

@danielstuart14, from my scripts.log: 
```
[...]
05.02.2016 19:49:19: Jawsh (10.0.0.7:2316) 12345678901234567890123456789012 - #2 ".sqf"




GUI_version = 1.063;
startloadingscreen [""];


createdialog "RscGUIEditor";
waituntil {!isnil {	(uinamespace getvaria"
05.02.2016 19:51:57: Jawsh (10.0.0.7:2316) 12345678901234567890123456789012 - #2 "inamespace getvariable "BIS_RscGUIEditor_exit")) then {


createdialog "RscGUIEditor";
GUI_listKeys = [];
waituntil {!isnil {	(u"
[...]
```

scripts.txt: 
```
[...]
// ".sqf\"\n\n\n\n\nGUI_version = 1.063;\nstartloadingscreen [\"\"];\n\n\ncreatedialog \"RscGUIEditor\";waituntil {!isnil {	(uinamespace getvaria" //Enter GUI Editor
// "inamespace getvariable \"BIS_RscGUIEditor_exit\")) then {\n\n\ncreatedialog \"RscGUIEditor\";\nGUI_listKeys = [];\nwaituntil {!isnil {	(u" //Exit GUI Editr
[...]
```


> By @DarkSilencerZA
> `7 "" !="removeBackpack this; removeAllWeapons this;" !"^["true", ""] [[\d:-]+ group, \d+]$"`
> `Use that in your remoteexec.txt`
> `Bam done`

Will test and commit sometime today.

**Comment by Jawshy** [comment]
Superseded by: #166

**Pull request closed without merging**
