### PR TITLE
Persistent Gear and Inventory

### PR DESCRIPTION
**Pull request by danielstuart14**
@Heavybob can you test it? And test these two config flags?

### CODE REVIEW

**Comment by Heavybob** [comment]
10:58:29 Error in expression <
_used = (_vehicle getVariable "Trunk") select 1;
_weight = [(typeOf _vehicle)] >
10:58:29   Error position: <select 1;
_weight = [(typeOf _vehicle)] >
10:58:29   Error Zero divisor
10:58:29 File mpmissions\__CUR_MP.Altis\core\vehicle\fn_vehicleWeight.sqf, line 13
10:58:29 Error in expression <
_used = (_vehicle getVariable "Trunk") select 1;
_weight = [(typeOf _vehicle)] >
10:58:29   Error position: <select 1;
_weight = [(typeOf _vehicle)] >
10:58:29   Error Zero divisor
10:58:29 File mpmissions\__CUR_MP.Altis\core\vehicle\fn_vehicleWeight.sqf, line 13
10:59:04 Generating ST on the fly is very slow

**Comment by Heavybob** [comment]
To get it to happen
Enable both trunk and gear *didn't test combinations* and that rpt error happens. 
Does not appear if both are false.

**Comment by danielstuart14** [comment]
are you sure about it? Didn't even touched in fn_vehicleWeight

Also, I tested by myself, and it seems to be working

**Comment by Heavybob** [comment]
hmm, will remerge main build
fn_vehicleweight

**Comment by tkcjesse** [comment]
@danielstuart14 might be the data being passed to it?

**Comment by Heavybob** [comment]
My veh weight is unchanged, must be something your code is phasing

**Comment by Heavybob** [comment]
Will test patches in a few hours.

**Comment by Heavybob** [comment]
testing all the commits
preparing

**Comment by clackd1amond** [comment]
I've just tested this. It's working

**Comment by Heavybob** [comment]
Right o, we shall find out the judgement from the lord Bob

**Comment by Heavybob** [comment]
Still no update on displaying how much inventory or fuel in the store menu?

**Comment by Heavybob** [comment]
Veh skin assigning is not working

**Comment by Heavybob** [comment]
Veh Skin does not assign properly when pulling cars out of garage

**Comment by clackd1amond** [comment]
Had no issues with that. Did you implement all Dan's color fixes?

**Comment by Heavybob** [comment]
wait, we got more problems

**Comment by Heavybob** [comment]
Its not saving inventory from what I can see.

**Comment by Heavybob** [comment]
My gear in my database is not saving and does this when I store in garage.

[]

**Comment by Heavybob** [comment]
"------------- Client Query Request -------------"
"QUERY: SELECT id, side, classname, type, pid, alive, active, plate, color, inventory, gear FROM vehicles WHERE id='200' AND pid='76561198010283300'"
"Time to complete: 0.00100708 (in seconds)"
"Result: [200,"civ","C_SUV_01_F","Car","76561198010283300",1,0,32439,18,"[]",""]"
"------------------------------------------------"

**Comment by clackd1amond** [comment]
http://prntscr.com/9sghy6

**Comment by Heavybob** [comment]
ts3222

**Comment by Heavybob** [comment]
Would ask that you recheck clak

**Comment by clackd1amond** [comment]
I've put even more stuff there. Then stored it. then unimpounded it. Everything was still there. I restarted the server and unimpounded the car again. Still worked. Fuel saves also.

DB

**Comment by Heavybob** [comment]
I rechecked what was going on. Confirmed it works. Sorry for the false alarm. Thanks for rechecking @clackd1amond 

Does Fuel Work?

**Comment by clackd1amond** [comment]
@Heavybob Yes. See my screenshot.

**Comment by Heavybob** [comment]
Confirmed, everything is working for this, will check textures now

**Comment by Heavybob** [comment]
Texture fix works. Thanks @danielstuart14

**Comment by Heavybob** [comment]
I would be good for a merge request to the main build with this.

**Pull request merged**
