### PR TITLE
Lets check if we impound our own vehicle

### PR DESCRIPTION
**Pull request by silvercn**

### CODE REVIEW

**Comment by sargken** [comment]
Don't think this should be added in since this is a framework. Just my opinion.

**Comment by dardothemaster** [comment]
@sargken this is a fix,read the file changed :) 

Great,this will disallow cops to make money impounding their own vehicles.

**Comment by Kimax89** [comment]
That "Merge remote-tracking branch" tho.

**Comment by clackd1amond** [comment]
Now they cops impound each other's vehicles. We need side check for vehicle, so cops couldn't impound any cop vehicle.

**Pull request merged**
