### PR TITLE
Some thing should be illegal.

### PR DESCRIPTION
**Pull request by Kimax89**
Changed the following items to `illegal = true;`:
Lockpick
Goldbar

Those items are only related to illegal activity.

### CODE REVIEW

**Comment by sargken** [comment]
Lockpicks aren't illegal but are used for illegal purposes this should be up tp server owners

**Comment by Kimax89** [comment]
the only reason why i think they should be illegal is because they are only ment for illegal purpose.

**Comment by Heavybob** [comment]
Agreed. Illegal but the reason they aren't marked is because of police searching. Lockpicks are usally stored between butt cheeks and hard to find.

**Comment by danielstuart14** [comment]
if you sell something in the civ market, then, it isn't illegal.

Gold can be set as illegal, if you want to redo a pull, I'll merge.

**Comment by Jawshy** [comment]
> if you sell something in the civ market, then, it isn't illegal.

So what about [bolt cutters](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/Config_vItems.hpp#L244-L253)?

**Pull request closed without merging**
