### PR TITLE
Add multi process

### PR DESCRIPTION
**Pull request by NiiRoZz**
You need to put that on init of NPC for use process : this
enableSimulation false;  this allowDamage false;  this
addAction[localize"STR_Process_Oil",life_fnc_processAction,"ExempleMultiProcess",0,false,false,"",'
!life_is_processing'];

Don't need to modify the line in NPC already place it's work with update.
You have an exemple of multi process in the case for exemple.

### CODE REVIEW

**Comment by N1colas62** [comment]
i go try this! :)
Thank!

**Comment by clackd1amond** [comment]
Thank you for this! Will test now. After that will post some new challenge for you :D

**Comment by NiiRoZz** [comment]
@N1colas62 and @clackd1amond Where are you from ?

**Comment by clackd1amond** [comment]
@NiiRoZz I'm from Ukraine. Why?

**Comment by NiiRoZz** [comment]
Let me know in gitter if you have any problem ...

**Pull request merged**
