### PR TITLE
Abort Timer Fix

### PR DESCRIPTION
**Pull request by trinitynet**
i was going to add another check in place for the spawn menu one but this does not seam necessary, through testing everything seams to work.

### CODE REVIEW

**Comment by Jawshy** [comment]
Abort timer is back, but now civilian position saving is not working. It saves the player's position in the database, but as soon as they hit abort and return to the lobby, `civ_position` is set to `"[0,0,0]"` and `civ_alive` to `0`. Upon reconnecting the player is prompted where to spawn.

**Comment by trinitynet** [comment]
i am not able to re-create this issue on my server, everything is working fine..

**Comment by fEcAlMaTteR** [comment]
@Jawshy Yea I'm getting this as well.  Due to server-side position check in the hc update.  Also defunkts the playtime data...  Fixing now will push in a few mins.

**Comment by fEcAlMaTteR** [comment]
https://github.com/ArmaLife/Altis/pull/403

Sorry, this was my fault PR fixes issue here.

**Comment by trinitynet** [comment]
@fEcAlMaTteR are many people using HC? as i seam to be the only one lol (apart from you)

**Comment by fEcAlMaTteR** [comment]
Apparently not since there would be alot of issues from it O.o

**Comment by trinitynet** [comment]
@fEcAlMaTteR do you have a discord or something? don't want to bog down GitHub with chitchat lol

**Comment by Jawshy** [comment]
@trinitynet, this and #404 fixes #392. However, after merging #404 there is a conflict. Could you please commit to fix and then I can merge.

**Comment by trinitynet** [comment]
Done... i think

**Comment by Jawshy** [comment]
Need `[] spawn life_fnc_escInterupt;` in Altis/Altis_Life.Altis/core/[fn_initCiv.sqf](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/fn_initCiv.sqf) and 
```sqf
if(playerSide == west || playerSide == independent) then 
{
	[] spawn life_fnc_escInterupt;
};
```
in Altis/Altis_Life.Altis/core/[init.sqf](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/init.sqf).

**Comment by fEcAlMaTteR** [comment]
@Jawshy Actually this is legit.  escInterupt is spawned in core/init and the if/then isn't needed. Conirmed working

**Comment by trinitynet** [comment]
@Jawshy  yeh that was my bad, left some debug code in

**Comment by Jawshy** [comment]
Cheers, guys.

**Comment by trinitynet** [comment]
happy to help :)

**Pull request merged**
