### PR TITLE
Update VehicleShop Part 2

### PR DESCRIPTION
**Pull request by Devilfloh**

### CODE REVIEW

**Comment by Heavybob** [comment]
What is a faction level?

**Comment by Devilfloh** [comment]
coplevel

factionlevel[] = { { "life_coplevel", "SCALAR", 3 }, { "", "", -1 } };

**Comment by Heavybob** [comment]
Why is it not just called coplevel since no other factions require this check?

**Comment by Devilfloh** [comment]
you can set life_medicLevel too if you want

**Comment by Heavybob** [comment]
I see... Just adopted the new structure with veh. Idea sounds good.

**Comment by clackd1amond** [comment]
Won't adding 'active='0'' to vehicleStore ruin the veh store cooldown system?

**Comment by Devilfloh** [comment]
oh you right
 sry

**Comment by NiiRoZz** [comment]
I have merged it but i just demand you if you put more information with new array in config vehicle;

**Comment by NiiRoZz** [comment]
For faction level.

**Comment by sargken** [comment]
I disagree on this merge.

**Comment by NiiRoZz** [comment]
Why explain, if you have a good reason i revert this merge

**Comment by Heavybob** [comment]
I also disagree with this merge, defining sides for each shop makes little sense. 
Why does a cop need to buy cars from reb or civ buying cars in police pd? 
This is kinda why the shops were separated to begin with. I understand that its condensing a bunch of brackets and commas but I argue prior to this commit it was fine. This commit also means that changes to the mission.sqm are required to be able to get cars out as a cop / ems for EVERYONE!

REVERT AHHHHHHHHHHHHHHHHHHHHHH!

**Comment by devShit** [comment]
then car shop npc will have no filter this cfg gonna filter it self. and civilian can retrive a car from police station swaG!!

**Comment by DarkSilencerZA** [comment]
Agreed. I don't even see why there were changes made to the splitting of money between cop / civ.

Being a cop and being a civ is almost the same as IRL. Cop = work, civ = chill. Why split it? I think there's too many shitty ideas being made to this main build. There should be a plan and a direction in where we are going. Not just slapping shit onto the git and then having to make 10 commits just to fix it. Some of us run this stuff on a live server - and if you can't test it then don't commit it.

**Comment by danielstuart14** [comment]
I didn't get why this new way to set shop cars... As I said sometime ago, if something works as it is supposed to, WHY CHANGE IT?

**Comment by sargken** [comment]
The split money also should be gone.

**Comment by sargken** [comment]
The issue is we have to talk about things before they are merged.

**Pull request merged**
