### PR TITLE
NearestBuilding --> NearestObjects (select 0)

### PR DESCRIPTION
**Pull request by dardothemaster**
Tested and working. Avoid to place two houses in similiar positions (<4meters) . This will detect both map placed and editor placed houses. 

If possible ,please test it in differents circumstances and write in the comments every problem so i'll  easily update the pull request without broking anything. 

----WATCH OUT----
When an house placed from the editor is deleted,make sure to remove the proper entry from the database!

Online,there is no a complete parameters guide on how to use nearestObject. Nearestobjects select 0 is the same thing.

Going to reopen when an eden mission.sqm gets pushed.

### CODE REVIEW

**Comment by devShit** [comment]
dardo noob

**Comment by dardothemaster** [comment]
Should i take it as a 'I've found an issue' ?

**Comment by danielstuart14** [comment]
working?

**Comment by dardothemaster** [comment]
Yes sorry forgot a commit:\

All okay

**Comment by danielstuart14** [comment]
also, isn't better nearestObject ? As if it return two houses it'll break the script

**Comment by dardothemaster** [comment]
I think that nearestObject does not allow the use of 'houses' general class,instead it requires specific classnames. Will investigate on it though.

**Comment by dardothemaster** [comment]
Ok,no way to use nearestObject

**Comment by danielstuart14** [comment]
nearestObjects can't be used since it'll return an array, and it'll break many of the script.

**Comment by dardothemaster** [comment]
Test it at least

**Comment by danielstuart14** [comment]
did you try with: nearestObject [_position, "House_F"]; ?

**Comment by dardothemaster** [comment]
No. Going to test it soon. In the meanwhile i close the pull as you said.

**Comment by dardothemaster** [comment]
Well so,the nearestObject [_position, "House_F"]; is not working as intended, it just selects every kind of house near the player. Not good as not all houses should be buyable.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/988915e481a3da09fade17d8a3832717e770b0de

thx

**Pull request closed without merging**
