### PR TITLE
Missing Backpacks

### PR DESCRIPTION
**Pull request by Heavybob**
Added missing Backpacks.

### CODE REVIEW

**Comment by Heavybob** [comment]
Stupid github fucked up my spaces again..

**Comment by clackd1amond** [comment]
Why did you remove { "NONE", "Remove Backpack", 0, { "", "", -1 } }, ?

**Comment by sargken** [comment]
He probably didnt mean to remove it.

**Comment by Heavybob** [comment]
thanks @sargken, accident on my part. 

If someone else wants to fix my stupid mistake that would be awesome. Looking at why persistent stats is being silly.

**Comment by sargken** [comment]
If i get time ill jack ur commit and do the fix.

**Comment by Heavybob** [comment]
I'll drop the missing hats in a sec

**Comment by sargken** [comment]
Then why don't u just take missing backpacks.

**Comment by Heavybob** [comment]
*CLOSED*
https://github.com/ArmaLife/Altis/pull/109

**Pull request closed without merging**
