### PR TITLE
Prevent I+Esc dupe

### PR DESCRIPTION
**Pull request by clackd1amond**
My suggestion of a fix against those unfairful players that I use on my server. The detailed procedure of this dupe method is discussed here: http://www.unknowncheats.me/forum/arma-3-a/142277-duplicate-body-items-weapons-clothing-etc.html

### CODE REVIEW

**Comment by Heavybob** [comment]
Will check this one out.

**Comment by Heavybob** [comment]
testing now

**Comment by Heavybob** [comment]
Works perfectly.

**Comment by sargken** [comment]
Good work man.

**Comment by tkcjesse** [comment]
I'd suggest removing..
diag_log format ["%1 (UID: %2) is a fucking duper!", player GVAR["realname",name player], getPlayerUID player];

Since it's only going to be logged client side anyways..?

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/4bda9568aea4d5ba0b36a6f0dfb04187cf026e62

**Comment by danielstuart14** [comment]
my question is: isn't 2 seconds too much? 
Maybe 0.5 already works... Can someone test it?
sleep 0.5;

**Comment by clackd1amond** [comment]
Personally I use sleep 0.5 in my server. But sometimes, especially on slower comps, such ssutiations happen when a player accidentally presses I insdead of U when he wants to lock/unlock his vehicle. So he presses esc to close inv menu. And while his esc-menu is loading, this script begins to work and strips down players. So I made it 2 secs to give a player time to close it manually. Or, if we won't use the strip down function as punishment, we can decrease sleep to 0.5 sec.

**Pull request closed without merging**
