### PR TITLE
Prevent Pmenu

### PR DESCRIPTION
**Pull request by tkcjesse**
Prevent player menu access whilst restrained

### CODE REVIEW

**Comment by Heavybob** [comment]
STOP SUBMITTING COMMITS!

**Comment by tkcjesse** [comment]
Fine. I'm done then. Not sure what your fucking problem is with me.
Simply contributing as I'm working on things of my own.

**Comment by Heavybob** [comment]
Join https://gitter.im/ArmaLife/Altis

I am not having a go at you, just having so many minor single changes is making me cross.

**Comment by tkcjesse** [comment]
No. I'm done here.

**Comment by danielstuart14** [comment]
guys, git is for commits as ocean is for water.
@tkcjesse you did a good job, and helped me a lot. Your help is appreciated.

**Comment by tkcjesse** [comment]
Not sure how long you guys have been around here for...
However if it's a while you'll know Tonic left it with Yuka, who basically did nothing as far as updating bugs was concerned. 
Now that this is finally being updated I felt I would contribute. That's all. Simply trying to help fix the things that are constantly asked on the forums... adding help for things that people ask a lot about. Considering the forums are EXTREMELY toxic where no one wants to help. @danielstuart14 it's nice to see that you have taken it upon yourself to further development.

**Comment by danielstuart14** [comment]
@tkcjesse @Heavybob was kidding. It's because I let him testing everything, and today we got commits to a next level.

You're helping a lot. I don't play altis too much, so, a commit from a player is gooddamm good.

I hope you stay on community.

**Comment by Heavybob** [comment]
@tkcjesse I am really sorry, please don't take my working offensively, I am Australian, I have an excuse to be rude. Just disregard my bad tone. I just checked the medic commit you did and its good. Thank you, you are a valuable person to be making commits to help everyone else. 

I am just a monster who is bad at typing friendly in txt.

**Comment by Heavybob** [comment]
Works. No errors. Merge Request please :+1: 

@tkcjesse Good work

**Pull request merged**
