### PR TITLE
HC Disabled by default.  HC_Required option

### PR DESCRIPTION
**Pull request by fEcAlMaTteR**
Headless client should be disabled by default.

HC_Required setting added to give the option to require the headless for the server to be ready for players.

### CODE REVIEW

**Comment by fEcAlMaTteR** [comment]
I'm going to suggest for now that if HC_Enabled = true to also set HC_Required = true unless you have a special need like us where the headless client isn't reliable enough to last the duration of a restart cycle.

**Comment by fEcAlMaTteR** [comment]
What's wrong with this?

**Comment by NiiRoZz** [comment]
You don't need create New HA required, look before, when HC disconnected auto merge to Life_server ..

**Comment by fEcAlMaTteR** [comment]
Most people wont need this setting but it was brought to my attention that it would be useful for certain situations.  I changed the hc initially because we run on linux which will not allow the hc to stay connected for more than 2.5 hours.  So we need a backup plan while the hc is restarting.  And it seemed odd to punish a player for joining the server at very beginning while the hc is still connecting.

**Comment by NiiRoZz** [comment]
It's not a problem, just if you active the HC, you need to wait HC connected for first query, but after if HC disconnect and reconnect you have eventhandler for that.

**Pull request closed without merging**
