### PR TITLE
Stats: Add persistent option for hunger and thirst

### PR DESCRIPTION
**Pull request by danielstuart14**
@Heavybob

### CODE REVIEW

**Comment by Heavybob** [comment]
Will test in a little bit.

**Comment by danielstuart14** [comment]
Can you test it enabled and disabled?

Things to test:
hunger and thirst (obviously)
Car spawn
Cop level
Medic level
House
Gangs

THX

**Comment by Heavybob** [comment]
Sure man, I'll test everything later.

**Comment by Heavybob** [comment]
testing now

**Comment by Heavybob** [comment]
RPT on spawn
life_gangData = (_this sel>
 2:07:20   Error position: <life_houses;

life_gangData = (_this sel>
 2:07:20   Error Undefined variable in expression: life_houses
 2:07:20 File mpmissions\__CUR_MP.Altis\core\session\fn_requestReceived.sqf, line 70
 2:07:20 Error in expression < select 10);
};
};
};

if(count ((_this select 14)) > 0) then {
{life_vehicles p>
 2:07:20   Error position: <select 14)) > 0) then {
{life_vehicles p>
 2:07:20   Error Zero divisor
 2:07:20 File mpmissions\__CUR_MP.Altis\core\session\fn_requestReceived.sqf, line 89
 2:07:20 Error in expression <using\fn_initHouses.sqf"






if(count life_houses == 0) exitWith {}; 

{
_posi>
 2:07:20   Error position: <life_houses == 0) exitWith {}; 

{
_posi>
 2:07:20   Error Undefined variable in expression: life_houses
 2:07:20 File mpmissions\__CUR_MP.Altis\core\housing\fn_initHouses.sqf, line 7
 2:07:20 Error in expression <ntrol\watertower_ca.paa"];
};

if(count life_houses > 0) then {
{
_pos = call co>
 2:07:20   Error position: <life_houses > 0) then {
{
_pos = call co>
 2:07:20   Error Undefined variable in expression: life_houses
 2:07:20 File mpmissions\__CUR_MP.Altis\dialog\function\fn_spawnPointCfg.sqf, line 32
 2:07:27 "Past Settings Init"
 2:07:27 "Executing client.fsm"
 2:07:27 "Display 46 Found"
 2:07:27 "------------------------------------------------------------------------------------------------------"
 2:07:27 "                End of Altis Life Client Init :: Total Execution Time 8.71387 seconds "
 2:07:27 "------------------------------------------------------------------------------------------------------"
 2:07:34 Client: Network message 12f3d (update info 644d46c8) is pending

**Comment by Heavybob** [comment]
*rpt attempt to buy a house*
 2:09:57   Error position: <life_houses >= (getNumber(missionConfigF>
 2:09:57   Error Undefined variable in expression: life_houses
 2:09:57 File mpmissions\__CUR_MP.Altis\core\housing\fn_buyHouse.sqf, line 17

**Comment by clackd1amond** [comment]
I had no errors. Be careful with those number on selects. They are very sensitive :)

**Comment by Heavybob** [comment]
I am going to wait out on this. Anything regarding database changes really makes me a little iffy.

**Comment by tkcjesse** [comment]
@clackd1amond did you use my pull request or this one? Dan changed some things when he wrote this one. The queryRequest file he did doesn't use an if then, causing the data to always be passed which will fuck up on the requestRecieved side.

**Comment by tkcjesse** [comment]
@danielstuart14 Note the differences in select statements between yours and mine. Hence why i had to do the if then. https://github.com/ArmaLife/Altis/blob/d9d18138b68d758cc65006a0bd9c4239b92b486e/life_server/Functions/MySQL/fn_queryRequest.sqf

**Comment by danielstuart14** [comment]
yeah, it should grep the stats from database anyway.
We shouldn't add an ifdef in database query.

Then, requestReceived would just select it if the config is defined... 
Don't know why it isn't working.

**Comment by tkcjesse** [comment]
@danielstuart14 Yeah gotcha. I don't see beyond that whats different between yours/mine. Hah.

**Comment by tkcjesse** [comment]
@clackd1amond did you test with with true/false or just true?

I've never tried this with the config_master options in there. I've always just had it how I wanted. So maybe it's something ordered wrong that way? However, doesn't look like it...

**Comment by clackd1amond** [comment]
@tkcjesse tested it with true. Will check 'false' now.

**Comment by tkcjesse** [comment]
@clackd1amond Thanks bud

**Comment by clackd1amond** [comment]
'false' works too, got my stats back to 100. And yes, I used your commit, @tkcjesse 
But now I have this error:
22:36:35 File mpmissions\__CUR_MP.Altis\core\session\fn_requestReceived.sqf, line 77
22:36:35 Error in expression <using\fn_initHouses.sqf"

if(count life_houses == 0) exitWith {}; 

{
_posi>
22:36:35   Error position: <life_houses == 0) exitWith {}; 

{
_posi>

With "save_playerStats = true;" no errors.

**Comment by clackd1amond** [comment]
oh wait...

**Comment by tkcjesse** [comment]
?

**Comment by clackd1amond** [comment]
Thought it was because of I had the same select for life_gangData and life_vehicles in fn_requestReceived.sqf, but when I fixed it, the error remained. It does something with houses and in multiple files. Look: http://pastebin.com/2TsuEg3V

**Comment by tkcjesse** [comment]
@clackd1amond  this is only when set to false though right?

I'll throw some diag_logs in it again and do the master config option in mine.... Had like 4 blocks of diag_logs when I did it without the config_master option lol... The ordering is so fucky

**Comment by danielstuart14** [comment]
tested and working without any RPT error.
(Enable/Disabled/COP/MED/CIV)

**Comment by tkcjesse** [comment]
Do you still want health & position or you gonna extend on that?

**Comment by clackd1amond** [comment]
I want :)

**Comment by sargken** [comment]
when loading in a dialog should appear for position, and ask if the user wants to spawn on previous position or just go to spawnmenu and pick the spawn. @tkcjesse you could expand it further to include previous vehicle position. Say server restart and they are in the middle of nowhere. If they choose previous position , there last vehicle they were in will spawn in with them there. Just a idea. @Heavybob, @danielstuart14, @tkcjesse - What do you guys think?

**Comment by tkcjesse** [comment]
The spawning vehicle thing would require far more work as you would have to add another field to the database to log what vehicle they had then use spawn vehicle to respawn that vehicle. Far more work than what I am willing to bother with honestly. And by offering the option to show the spawn menu, it allows people to log out and be just fine and keep their position when its good for them.. I'll be offering an implementation where you either accept your spawn with your items, etc at your last position or forfeit your gear due to re-spawning back at a Spawn point. Not right in my opinion to be able to just "town hop" with all your gear. For example, you log out at a rebel with a loadout and now you can just spawn in a town with all that gear, no travel required. Or hop from town to town. That's the nice thing with persistent position..

**Comment by clackd1amond** [comment]
Completely agree. When I had position saving on previous builds player asked for an option in spawn menu but I didn't do it. btw this thing is true for a persistant trunk. For example, you spawn at cavala, gather resource. Then store your car and do the relog. In a minute you are in Sofia at the processing. In a next minute you are in Pyrgos selling it

**Comment by tkcjesse** [comment]
Mmm... Never even thought of that... ^ thats a good point. I've never done trunk storing. Now I def won't be haha.

**Comment by clackd1amond** [comment]
Well I've seen cool thing on one server: you can spawn a car only where you stored it

**Comment by tkcjesse** [comment]
Otherwise a timer that's set if you store it with stuff inside would work too

**Comment by clackd1amond** [comment]
It would be even better. No need to save garages to db

**Pull request merged**
