### PR TITLE
Vehicle Gear & Virt Items Save

### PR DESCRIPTION
**Pull request by sargken**
This includes the saving gear and virtual items. @Heavybob Can you test this a final time.

### CODE REVIEW

**Comment by Heavybob** [comment]
From what I can see, no issues with this change and works perfectly as designed when enabled.
Good work @sargken

**Comment by sargken** [comment]
@danielstuart14 You can check it over now, i removed the call from open inventory. So that shouldn't be an issue.

**Comment by Heavybob** [comment]
@sargken I just msged you on discord but I would hold this commit for one last thing. 

Players who own a shitload of Veh will not know which ones hold the shipments of drugs or gear. 
http://images.akamai.steamusercontent.com/ugc/365156556371327909/68AC81EA75ED81E1831CC4678ED0B10465ADEE99/

I propose Fuel Capacity it shows

Trunk Inventory: *number of items*
Gear Inventory:*number of items*

I won't show what type of items are in them but would show that they actually have items in them.

**Comment by sargken** [comment]
I will see what i can do.

**Comment by Heavybob** [comment]
Would also put an option to store gold bars or not in veh. I believe you are unable in houses but I could be wrong.

**Comment by Heavybob** [comment]
Just another thought experiment, if your car get impounded, does it save the inventory? If so lets say you are robbing fed reserve and you impound a hem with 100 gold bars. Does it go into garage? 

Probs wana put a check for that too.

**Comment by Heavybob** [comment]
Typo in Strings STR_Shop_Veh_UI_Gear
ammount = amount

**Comment by Heavybob** [comment]
http://hastebin.com/wayuzapumi.tex
Bugs out display of Veh Impound and Garage

**Comment by Heavybob** [comment]
Testing fix, update in 5 mins

**Comment by Heavybob** [comment]
http://hastebin.com/orudovisov.tex
Will not display listed Veh in Garage and Shop Menu.

**Comment by Heavybob** [comment]
testing

**Comment by Heavybob** [comment]
http://hastebin.com/owufuridaz.tex

**Comment by sargken** [comment]
@Heavybob I don't know if we can do the show gear and virt items count in garage, because it doesn't seem want to call a query from the database. I'm trying to call it from the mission and it doesn't want to pick up the script server side.

**Comment by danielstuart14** [comment]
ok, revert it as it was before the garage count. I'll merge.

It isn't essential... We can look later.

**Comment by sargken** [comment]
Ok will do.

**Comment by sargken** [comment]
@Heavybob Can you test this, revert back to original. Want to make sure its functioning like it was before i pass it onto dan.

**Comment by Heavybob** [comment]
right o, about to test
put // experimental into the master_config

**Comment by sargken** [comment]
why would you do that? this is the build that should work nothing wrong here.

**Comment by sargken** [comment]
@danielstuart14 No issues All good to go according to @Heavybob

**Pull request closed without merging**
