### PR TITLE
Clothing Preview - Dynamic Position

### PR DESCRIPTION
**Pull request by sargken**
This includes the dynamic positioning for clothing shops. @Heavybob Can you test this a final time.

### CODE REVIEW

**Comment by Heavybob** [comment]
Sure, give me a few mins

**Comment by Heavybob** [comment]
No errors. Works perfectly.

**Comment by sargken** [comment]
@Heavybob The values you gave me are the default values being used. No need now if they wish to change them they can just add them in.

**Comment by Heavybob** [comment]
Thats what I mean, it works fine. No need to say preview or WIP, it works perfectly and does not need anything further changed.

**Comment by Heavybob** [comment]
@sargken Its not an issue, just explaining to those server owners.

If you do not set custom clothing store locations in fn_clothingMenu.sqf on line 47 then you will end up here.

107410_screenshots_2016-01-19_00003]

Commit works perfectly, no issues. Happy for this to be added to main build.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/ced728fe883a34d22d20f19c38a8392d9c97652f

Fixes preview in not set stores and fixes near vehicles

**Pull request merged**
