### PR TITLE
New Phone Request

### PR DESCRIPTION
**Pull request by TravisPrice**
This is something I worked on and maybe it could replace the Y menu currently if you would like to see it you can go here http://www.altisliferpg.com/topic/13560-tutorial-new-phone/

### CODE REVIEW

**Comment by sargken** [comment]
Its a great idea but i think we would have to take a vote for a new menu.

**Comment by danielstuart14** [comment]
sometime ago, Tonic sent me a msg with a phone menu that sa-matra had developed, he asked me to merge it. But it didn't work.

Afaik, this phone menu is very similar, and it is pretty good. I think we just need to change the pos and maybe the background. That's it.

I'll test today

**Comment by TravisPrice** [comment]
Okay cool yah background changes will be easy on another hand positioning we may have to redo the gui but either which is fine

**Comment by silvercn** [comment]
I tested it already and yeah its not finished yet, some things open in a normal window instead of phone menu. Also it has no multi support for languages, thats the only reason i would not use it.

**Comment by sargken** [comment]
I ported the one from Asylum Life it works great.

**Comment by Jawshy** [comment]
Some of the file changes are out-of-date and would re-introduce old issues. Example: [fn_useItem.sqf, line 70](https://github.com/TravisPrice/Altis/commit/6996810a1c045a6d9c17a5f7df56e6c98b499b49#diff-90e0d41404b30299d6c29ff41405f2beR70)

**Comment by Liam0** [comment]
New interface would be amazing. but it shoulden't be copied from somewhere else would be nice if it was unique to AltisLife

**Comment by TravisPrice** [comment]
I can fix these simple issues which is why I said report it just message me or put it here and I will get right to it

**Comment by TravisPrice** [comment]
And yah it's not done I put that in the thread title most of which it is done on the side of working now got to add more stuff meaning the stuff that pops up in original window

**Comment by devShit** [comment]
oh snap

**Comment by danielstuart14** [comment]
Merged, I'm going to take a look in the background later.

**Comment by danielstuart14** [comment]
Here is the background and icons tonic sent me... If someone wants to add it, would be great.

https://drive.google.com/file/d/0B7tAoe6NC6GYVURIRzMzc3ZpMTQ/view?usp=sharing

**Pull request merged**
