### PR TITLE
Adjustable jail settings

### PR DESCRIPTION
**Pull request by Kimax89**
This havent been tested yet, so i have no idea if it will work.

Can someone please look this through and check if everything is correct?

### CODE REVIEW

**Comment by Jawshy** [comment]
The `jail_bail_amount` should be equal to the player's bounty. The higher the wanted list bounty the higher the bail price. Unless that's the default amount if the player being jailed doesn't have a wanted list bounty.

**Comment by Kimax89** [comment]
It should only be the default amount.

`if(count _ret > 0) then { life_bail_amount = SEL(_ret,3); } else { life_bail_amount = _bailamount; };`

**Comment by AmarokGaming** [comment]
This tested yet?

**Comment by Kimax89** [comment]
not yet, but i'm testing it this weekend.

**Comment by Kimax89** [comment]
Leave a comment

**Comment by tkcjesse** [comment]
@Kimax89 Are you still doing this?

**Pull request closed without merging**
