### PR TITLE
Persistent Fuel Storage

### PR DESCRIPTION
**Pull request by tkcjesse**
I mean, we do have gas cans in the game for a reason... As well as refueling at fuel stations. All I know is I wish my vehicle refueled in my garage IRL....

### CODE REVIEW

**Comment by Heavybob** [comment]
Will test in a few moments.

**Comment by sargken** [comment]
Will cause conflicts with #34

**Comment by tkcjesse** [comment]
As I've stated before...  15 additions and 12 deletions. on 3 files that actually matter... Literally adding just   "fuel" in them basically... To add them to yours wouldn't be hard. Plus yours is a WIP? I will not be constantly adjusting this to fit a WIP merge request...

**Comment by Heavybob** [comment]
Can you test this tkc and would you kindly include the latest builds changes into this then test. 

Does this merge display the fuel left in the Veh when its being pulled out of the Garage? If not then probs wana do that before applying the commit because having an empty car in your garage and not be able to pull it out and drive. For me who has 100 cars in my garage, I would have to fiddle for hours to find a car with fuel in it. 

Thoughts?

**Comment by Heavybob** [comment]
Can this be closed due to https://github.com/ArmaLife/Altis/pull/61

**Pull request closed without merging**
