### PR TITLE
Persistent Messaging Using Database

### PR DESCRIPTION
**Pull request by sargken**
I suggest we stick to using the database as long as it does not create
too much data for it to be passed. @Heavybob How is it looking and can u post a pic of the phone dialog. @danielstuart14 I suggest keeping the database as it offers more capabilities for web based programs to interact with the game. Or make it a config setting where it can save to database or it can just be a temp thing.

### CODE REVIEW

**Comment by sargken** [comment]
@heavybob you ever get a change to review this?

**Comment by Heavybob** [comment]
Have not had a go yet. Been busy with working on the new battle eye and other issues. 
Will eventually test this but not in my tired state.

**Comment by ColinM9991** [comment]
As great as this is, I'd personally say it might be worthwhile looking at creating a new cell-phone system with database persistence that works more dynamically and fluid with extra error-prone implementations.

One issue for example is the "Error: No Name" issue - which could be resolved by storing GUID's and using INNER JOIN on the players table in order to fetch the name and return to the requester (cell phone operator) thus removing atomic data & normalizing the database and using what data is already available and reliable.

Another idea if a new phone system were to be created would be to include a government type system where people get message alerts of incoming payments (social welfare) and store in their phone from a default number like 50220, you can then place pluggable alerts on the phone interface so if somebody has a tax system they can easily use the provided API to place an alert that tax is due in x amount of minutes or hours.

**Comment by Heavybob** [comment]
Still haven't gotten to testing this because I have been busy trying to sort out the new battle eye filters. Will work on getting to this.

**Comment by sargken** [comment]
@ColinM9991 That could be something that we could work on for down the road. This could be a framework laid out.

**Comment by Heavybob** [comment]
Bump?

**Comment by tkcjesse** [comment]
If I recall Dan wants to just do like the last 10 minutes and have it based on your session rather than DB storage.

**Comment by danielstuart14** [comment]
So, the thing is. 
I'll merge it, but only when I get time for. (And I'm really busy right now, I know, that seems like bullshit, but it isn't.)

BUT, I probably will add it when the new phone UI get ready. It'll display the last 10 messages by default, but, will have a persist DB option

**Comment by danielstuart14** [comment]
not working.

**Pull request closed without merging**
