### PR TITLE
Position & Damage Saving

### PR DESCRIPTION
**Pull request by tkcjesse**
Initial upload. Is always enabled. It's possible I forgot something in
here... pretty sure this is everything though. If you have issues message me on Gitter with your RPT log ready
and I can assist.

### CODE REVIEW

**Comment by danielstuart14** [comment]
going to add as array, thx @tkcjesse

**Comment by tkcjesse** [comment]
No problem. Wasn't sure how you wanted to do array stuff and what type of Config_master settings.

**Comment by sargken** [comment]
Great work Jesse, looking good.

**Comment by Heavybob** [comment]
Looks good. Will wait a few hours before checking. Nice work Jesse

**Comment by Heavybob** [comment]
Going to need to adjust with the new changes including playtime.

**Comment by magicianaos** [comment]
My position save idea.

Using tent backpack(B_Respawn_TentDome_F).

Tent position save the DB and respawn saved tent position.

What do you think?

**Comment by NiiRoZz** [comment]
I have a problem with this, with : 
Player Position : When server restart (crash or anything else ) and you are in fields you are 2 solutions : suicide or run, but you run 4 kilometer, take big time .
Tent position : the same or just you can place but only for 1 respawn on this ...

**Comment by magicianaos** [comment]
Tent add action menu
Use action menu, then tent & player position save at DB.
How about that?

**Comment by clackd1amond** [comment]
@NiiRoZz I use position saving on my sever. And when server restarts, it runs a procedure in database that clears last positions, so everybody after the restart can select spawn point again.

**Comment by Heavybob** [comment]
Can vouch that persons in the middle of the ocean during a restart will suffer from position saving.

**Comment by N1colas62** [comment]
any news ? :+1:

**Comment by Heavybob** [comment]
Not merged due to conflicts, they separated all the repos so this change will have to be resubmitted.

**Comment by tkcjesse** [comment]
Daniel is working on it.  Not me anymore.

**Pull request closed without merging**
