### PR TITLE
Update fn_vInteractionMenu.sqf

### PR DESCRIPTION
**Pull request by Shems-SA**

### CODE REVIEW

**Comment by Heavybob** [comment]
Testing before commit is made to make sure interaction menu is fixed.

**Comment by Shems-SA** [comment]
yes i've tested it

**Comment by Heavybob** [comment]
Cannot be too careful. Submitting results in a few mins

**Comment by Heavybob** [comment]
Thanks for fixing @Shems-SA, No issues that can be seen.

Approved @danielstuart14

**Comment by Heavybob** [comment]
107410_screenshots_2016-01-28_00001

What could this be?

**Comment by Heavybob** [comment]
Looks like flip is blank on DLC stuff but is seen on non dlc stuff.

**Comment by Shems-SA** [comment]
because you've the DLC ... I'll find another way

**Comment by Heavybob** [comment]
Flip is universally broken and cannot be executed on any veh.

**Comment by Shems-SA** [comment]
perhaps this is less clean but I think it will work: http://pastebin.com/X36LS9Jp

**Comment by Heavybob** [comment]
testing, give me a moment

**Comment by Shems-SA** [comment]
Just add stringtable : <Key ID="STR_vInAct_GetInVeh">
      <Original>Get In Vehicle</Original>
      <German>Ins Fahrzeug setzen</German>
      <French>Monter dans le véhicule</French>
      <Italian>Entra nel veicolo</Italian>
      <Portuguese>Entrar no veículo</Portuguese>
      <Polish>Wejdź do pojazd</Polish>
    </Key>

**Comment by Heavybob** [comment]
Already have it from the previous commit you made. I try to keep up to date :+1:

**Comment by Heavybob** [comment]
Still no dice, issue still persists. On gitter if you want to talk more about this. 

*Opt for revert on fn_vInteractionMenu.sqf till this is cleaned up. *

*Reply on gitter*
@danielstuart14 
Hey heavy, tomorrow I'm home. Will revert it and do in the right way

**Pull request closed without merging**
