### PR TITLE
Disable getIn and getOut for restrained players

### PR DESCRIPTION
**Pull request by danielstuart14**
@tkcjesse 
Pls, try all the possibilities with restrained players.

:D

### CODE REVIEW

**Comment by tkcjesse** [comment]
@danielstuart14 Won't be able to tonight probably. I'll get back to ya.

**Comment by danielstuart14** [comment]
okay, not a problem!

**Comment by Jawshy** [comment]
@danielstuart14, said: 
> Just need someone to test (All possibilities: move to driver/get out in high speed/get out flying/etc)

I'll see if I can get someone to test with me sometime today.

**Comment by Jawshy** [comment]
@danielstuart14: 
- Civilians that have been restrained will be ejected from the vehicle if they attempt to enter any seat. 
- Civilians that have been restrained and put into a vehicle by police can switch to the driver's seat and drive off if the vehicle is unlocked. However, they cannot exit the vehicle and attempting to do so moves them to the passenger seat.

**Comment by danielstuart14** [comment]
It should work now

**Comment by Jawshy** [comment]
From Gitter chat: 
> Restrained civs in vehicles cannot go as driver; they get kicked out. 
> _[...]_
> @danielstuart14, A restrained civilian can enter / exit vehicles they can reach, but they should not be able to do so because then the civilian can simply exit the vehicle when a cop goes to unlock it so the cop can take the civilian to jail, or where-ever.

**Pull request closed without merging**
